added expanded text color to provide more customization
Skylled/expansion_tile_card pull request #13
Opened 2020-08-05 18:07 UTC by msandwidi

I found myself going in the source code to change the color of the text when the tile is expanded. As of now, the color is set to the accent color provided by the context and there is now way to change it unless you go in you local source code to do it. 

I added a property called `expandedTextColor ` and set its default value to the `accentColor `of the theme.  

so from 

```
  @override
  void didChangeDependencies() {
    final ThemeData theme = Theme.of(context);
    _headerColorTween
      ..begin = theme.textTheme.subtitle1.color
      ..end = theme.accentColor;
    _iconColorTween
      ..begin = theme.unselectedWidgetColor
      ..end = theme.accentColor;
    _materialColorTween
      ..begin = widget.baseColor ?? theme.canvasColor
      ..end = widget.expandedColor ?? theme.cardColor;
    super.didChangeDependencies();
  }
```
 to 

```
final Color expandedTextColor ;

@override
  void didChangeDependencies() {
    final ThemeData theme = Theme.of(context);
    _headerColorTween
      ..begin = theme.textTheme.subtitle1.color
      ..end = widget.expandedTextColor ?? theme.accentColor;
    _iconColorTween
      ..begin = theme.unselectedWidgetColor
      ..end = widget.expandedTextColor ?? theme.accentColor;
    _materialColorTween
      ..begin = widget.baseColor ?? theme.canvasColor
      ..end = widget.expandedColor ?? theme.cardColor;
    super.didChangeDependencies();
  }
```

2020-08-25 09:30 UTC, kazumaz commented
I wanna this pull request to be merged...

2020-08-25 17:24 UTC, Skylled requested changes
Sorry this took so long. It fell off my radar.

Looks great! Just one super minor change and we can merge.

2020-08-25 17:24 UTC, Skylled commented on lib/expansion_tile_card.dart
> +  ///If null, defaults to Theme.of(context).accentColor.
```suggestion
  /// The color of the text of the expended card
  ///
  /// If null, defaults to Theme.of(context).accentColor.
```
Nit: Space before comments.

2020-08-26 02:38 UTC, msandwidi commented on lib/expansion_tile_card.dart
> +  ///If null, defaults to Theme.of(context).accentColor.
Looks good. Thanks

2020-08-26 02:42 UTC, msandwidi reviewed
It looks good.

2020-08-26 20:31 UTC, merged